#!/bin/bash
NODES=1000
MAX_EDGES=$(($NODES * ($NODES - 1) / 2))

mkdir -p benchmarks/local

for i in $(seq 100); do
	EDGES=$(($NODES * $i / 100))
	sh run-client $NODES $EDGES > benchmarks/local/$i
done
		
