Console.Writeline("<!DOCTYPE html>");
Console.Writeline("<html lang="en" xmlns="http://www.w3.org/1999/xhtml">");
Console.Writeline("<head>");
Console.Writeline("	<meta charset="utf-8" />");
Console.Writeline("	<title>Nezarka.net: Online Shopping for Books</title>");
Console.Writeline("</head>");
Console.Writeline("<body>");
Console.Writeline("	<style type="text/css">");
Console.Writeline("		table, th, td {");
Console.Writeline("			border: 1px solid black;");
Console.Writeline("			border-collapse: collapse;");
Console.Writeline("		}");
Console.Writeline("		table {");
Console.Writeline("			margin-bottom: 10px;");
Console.Writeline("		}");
Console.Writeline("		pre {");
Console.Writeline("			line-height: 70%;");
Console.Writeline("		}");
Console.Writeline("	</style>");
Console.Writeline("	<h1><pre>  v,<br />Nezarka.NET: Online Shopping for Books</pre></h1>");
Console.Writeline("	Jan, here is your menu:");
Console.Writeline("	<table>");
Console.Writeline("		<tr>");
Console.Writeline("			<td><a href="/Books">Books</a></td>");
Console.Writeline("			<td><a href="/ShoppingCart">Cart (2)</a></td>");
Console.Writeline("		</tr>");
Console.Writeline("	</table>");
Console.Writeline("	Our books for you:");
Console.Writeline("	<table>");
Console.Writeline("		<tr>");
Console.Writeline("			<td style="padding: 10px;">");
Console.Writeline("				<a href="/Books/Detail/1">Lord of the Rings</a><br />");
Console.Writeline("				Author: J. R. R. Tolkien<br />");
Console.Writeline("				Price: 59 EUR &lt;<a href="/ShoppingCart/Add/1">Buy</a>&gt;");
Console.Writeline("			</td>");
Console.Writeline("			<td style="padding: 10px;">");
Console.Writeline("				<a href="/Books/Detail/2">Hobbit: There and Back Again</a><br />");
Console.Writeline("				Author: J. R. R. Tolkien<br />");
Console.Writeline("				Price: 49 EUR &lt;<a href="/ShoppingCart/Add/2">Buy</a>&gt;");
Console.Writeline("			</td>");
Console.Writeline("			<td style="padding: 10px;">");
Console.Writeline("				<a href="/Books/Detail/3">Going Postal</a><br />");
Console.Writeline("				Author: Terry Pratchett<br />");
Console.Writeline("				Price: 28 EUR &lt;<a href="/ShoppingCart/Add/3">Buy</a>&gt;");
Console.Writeline("			</td>");
Console.Writeline("		</tr>");
Console.Writeline("		<tr>");
Console.Writeline("			<td style="padding: 10px;">");
Console.Writeline("				<a href="/Books/Detail/4">The Colour of Magic</a><br />");
Console.Writeline("				Author: Terry Pratchett<br />");
Console.Writeline("				Price: 159 EUR &lt;<a href="/ShoppingCart/Add/4">Buy</a>&gt;");
Console.Writeline("			</td>");
Console.Writeline("			<td style="padding: 10px;">");
Console.Writeline("				<a href="/Books/Detail/5">I Shall Wear Midnight</a><br />");
Console.Writeline("				Author: Terry Pratchett<br />");
Console.Writeline("				Price: 31 EUR &lt;<a href="/ShoppingCart/Add/5">Buy</a>&gt;");
Console.Writeline("			</td>");
Console.Writeline("		</tr>");
Console.Writeline("	</table>");
Console.Writeline("</body>");
Console.Writeline("</html>");
