Console.Writeline("<!DOCTYPE html>");
Console.Writeline("<html lang="en" xmlns="http://www.w3.org/1999/xhtml">");
Console.Writeline("<head>");
Console.Writeline("	<meta charset="utf-8" />");
Console.Writeline("	<title>Nezarka.net: Online Shopping for Books</title>");
Console.Writeline("</head>");
Console.Writeline("<body>");
Console.Writeline("	<style type="text/css">");
Console.Writeline("		table, th, td {");
Console.Writeline("			border: 1px solid black;");
Console.Writeline("			border-collapse: collapse;");
Console.Writeline("		}");
Console.Writeline("		table {");
Console.Writeline("			margin-bottom: 10px;");
Console.Writeline("		}");
Console.Writeline("		pre {");
Console.Writeline("			line-height: 70%;");
Console.Writeline("		}");
Console.Writeline("	</style>");
Console.Writeline("	<h1><pre>  v,<br />Nezarka.NET: Online Shopping for Books</pre></h1>");
Console.Writeline("	Jan, here is your menu:");
Console.Writeline("	<table>");
Console.Writeline("		<tr>");
Console.Writeline("			<td><a href="/Books">Books</a></td>");
Console.Writeline("			<td><a href="/ShoppingCart">Cart (2)</a></td>");
Console.Writeline("		</tr>");
Console.Writeline("	</table>");
Console.Writeline("	Book details:");
Console.Writeline("	<h2>Going Postal</h2>");
Console.Writeline("	<p style="margin-left: 20px">");
Console.Writeline("	Author: Terry Pratchett<br />");
Console.Writeline("	Price: 28 EUR<br />");
Console.Writeline("	</p>");
Console.Writeline("	<h3>&lt;<a href="/ShoppingCart/Add/3">Buy this book</a>&gt;</h3>");
Console.Writeline("</body>");
Console.Writeline("</html>");
