Console.Writeline("<!DOCTYPE html>");
Console.Writeline("<html lang="en" xmlns="http://www.w3.org/1999/xhtml">");
Console.Writeline("<head>");
Console.Writeline("	<meta charset="utf-8" />");
Console.Writeline("	<title>Nezarka.net: Online Shopping for Books</title>");
Console.Writeline("</head>");
Console.Writeline("<body>");
Console.Writeline("	<style type="text/css">");
Console.Writeline("		table, th, td {");
Console.Writeline("			border: 1px solid black;");
Console.Writeline("			border-collapse: collapse;");
Console.Writeline("		}");
Console.Writeline("		table {");
Console.Writeline("			margin-bottom: 10px;");
Console.Writeline("		}");
Console.Writeline("		pre {");
Console.Writeline("			line-height: 70%;");
Console.Writeline("		}");
Console.Writeline("	</style>");
Console.Writeline("	<h1><pre>  v,<br />Nezarka.NET: Online Shopping for Books</pre></h1>");
Console.Writeline("	Jan, here is your menu:");
Console.Writeline("	<table>");
Console.Writeline("		<tr>");
Console.Writeline("			<td><a href="/Books">Books</a></td>");
Console.Writeline("			<td><a href="/ShoppingCart">Cart (3)</a></td>");
Console.Writeline("		</tr>");
Console.Writeline("	</table>");
Console.Writeline("	Your shopping cart:");
Console.Writeline("	<table>");
Console.Writeline("		<tr>");
Console.Writeline("			<th>Title</th>");
Console.Writeline("			<th>Count</th>");
Console.Writeline("			<th>Price</th>");
Console.Writeline("			<th>Actions</th>");
Console.Writeline("		</tr>");
Console.Writeline("		<tr>");
Console.Writeline("			<td><a href="/Books/Detail/1">Lord of the Rings</a></td>");
Console.Writeline("			<td>3</td>");
Console.Writeline("			<td>3 * 59 = 177 EUR</td>");
Console.Writeline("			<td>&lt;<a href="/ShoppingCart/Remove/1">Remove</a>&gt;</td>");
Console.Writeline("		</tr>");
Console.Writeline("		<tr>");
Console.Writeline("			<td><a href="/Books/Detail/5">I Shall Wear Midnight</a></td>");
Console.Writeline("			<td>1</td>");
Console.Writeline("			<td>31 EUR</td>");
Console.Writeline("			<td>&lt;<a href="/ShoppingCart/Remove/5">Remove</a>&gt;</td>");
Console.Writeline("		</tr>");
Console.Writeline("		<tr>");
Console.Writeline("			<td><a href="/Books/Detail/3">Going Postal</a></td>");
Console.Writeline("			<td>1</td>");
Console.Writeline("			<td>28 EUR</td>");
Console.Writeline("			<td>&lt;<a href="/ShoppingCart/Remove/3">Remove</a>&gt;</td>");
Console.Writeline("		</tr>");
Console.Writeline("	</table>");
Console.Writeline("	Total price of all items: 236 EUR");
Console.Writeline("</body>");
Console.Writeline("</html>");
